version: '3.8'
services:
  web:
    build: ./flask-example
    ports:
      - "5000:8080"
  static:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
